### ISSUE TITLE
INFOGRAFÍA HILOS EN CONSOLA EN C#

### ISSUE THREAD

**Issue by Litzy-lopez4** [SistemasTecTlaxiaco/infografia-de-hilos-Litzy-lopez4#2]
[INFOGRAFIA HILOS EN CONSOLA EN C#.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Litzy-lopez4/files/8373412/INFOGRAFIA.HILOS.EN.CONSOLA.EN.C.pdf)

**Comment by Heidi-19** [comment]
calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
